package com.dominikdomotor.nextcloudpasswords.ui.theme

import android.annotation.SuppressLint
import android.content.Context
import android.content.res.Configuration
import android.os.Build
import androidx.appcompat.app.AppCompatDelegate
import com.dominikdomotor.nextcloudpasswords.GF
import com.dominikdomotor.nextcloudpasswords.dataclasses.ThemeMode
import com.google.android.material.color.ColorResourcesOverride

/**
 * Points the app's colour resources at a palette generated from the seed.
 *
 * The trick is which half moves. A theme attribute cannot be handed an arbitrary colour at runtime, so the theme stays
 * completely static - `Theme.NextcloudPasswords` maps every Material role at a `@color/npac_*` resource once, at build
 * time - and it is the *values* of those resources that get replaced here, through a `ResourcesLoader`. Every widget,
 * drawable and ripple that already resolves `?attr/colorSurface` therefore follows the seed with no further work.
 *
 * On Android 10 there is no loader, so the static defaults in `values/theme_colors.xml` are what the app paints with.
 * They were generated by the same [PaletteGenerator] from the same default seed, so that build is a coherent palette
 * rather than a degraded one - it just cannot be re-seeded.
 */
object ThemeApplier {
    /**
     * Applies [theme] to [context], which must be an activity, before anything has been inflated.
     *
     * Failure is swallowed on purpose. This runs inside `onCreate` on the path to the first frame, and the worst
     * outcome of a loader that will not attach is the app looking like its default self - not worth a crash loop that
     * leaves the user no way back into their passwords.
     */
    fun apply(context: Context, theme: AppTheme = ThemeCache.read(context)) {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.R) return
        val palette = PaletteGenerator.generate(theme.seed, isDark(context), theme.mode.isAmoled, theme.tintedText)
        runCatching { attach(context, palette) }
            .onFailure { GF.println("Palette not applied, keeping the static defaults: ${it.message}") }
    }

    /**
     * The night mode a [ThemeMode] implies.
     *
     * AMOLED collapses to "yes": it is a flavour of dark rather than a mode of its own, and the black surfaces come
     * from the palette, not from the night-mode setting.
     */
    fun nightModeFor(mode: ThemeMode): Int =
        when (mode) {
            ThemeMode.SYSTEM -> AppCompatDelegate.MODE_NIGHT_FOLLOW_SYSTEM
            ThemeMode.LIGHT -> AppCompatDelegate.MODE_NIGHT_NO
            ThemeMode.DARK,
            ThemeMode.AMOLED -> AppCompatDelegate.MODE_NIGHT_YES
        }

    /**
     * Hands the palette to the resource system, keyed by resource id.
     *
     * `ColorResourcesOverride` builds an in-memory ARSC and attaches it as a `ResourcesLoader`, which is not something
     * worth reimplementing - the class that does the building is package-private, so this public façade is the only way
     * in. It is `@RestrictTo`, hence the suppression, kept to this one file.
     *
     * It also force-applies Material's `ThemeOverlay.Material3.PersonalizedColors`, which re-points every M3 role at
     * Material's own `material_personalized_color_*` resources - so it would otherwise undo the mapping our theme
     * declares and hand the app baseline purple. The answer is to override *both* id sets with the same values, so it
     * no longer matters which mapping wins. Those resources are private to Material, but private only blocks a
     * compile-time `R` reference: they are merged into our package, so looking them up by name at runtime is fine.
     */
    @SuppressLint("RestrictedApi")
    private fun attach(context: Context, palette: Map<String, Int>) {
        val byId = mutableMapOf<Int, Int>()
        val unmapped = mutableListOf<String>()
        palette.forEach { (name, color) ->
            val id = idOf(context, name)
            if (id == null) unmapped += name else byId[id] = color
            materialTwinsOf(name).forEach { twin -> idOf(context, twin)?.let { byId[it] = color } }
        }
        // A slot the generator produces but the XML never declared can never be painted: the screen keeps the previous
        // colour there, which reads as one subtly wrong shade rather than as a mistake. Say so.
        if (unmapped.isNotEmpty()) GF.println("Palette slots missing from theme_colors.xml: $unmapped")

        ColorResourcesOverride.getInstance()?.applyIfPossible(context, byId)
    }

    /**
     * Material's own resource names for the same role.
     *
     * Mostly a prefix swap; the exceptions are the few places Material orders the words the other way round, and the
     * AppCompat bridge names, which have no slot of their own because they are aliases for roles we already generate. A
     * missing name is not an error - `surface_tint` and `scrim` simply have no Material twin.
     */
    private fun materialTwinsOf(slot: String): List<String> {
        val prefixed = slot.replace("npac_", "material_personalized_color_")
        return when (slot) {
            "npac_inverse_primary" -> listOf("material_personalized_color_primary_inverse")
            "npac_inverse_surface" -> listOf("material_personalized_color_surface_inverse")
            "npac_inverse_on_surface" -> listOf("material_personalized_color_on_surface_inverse")
            "npac_ripple" -> listOf("material_personalized_color_control_highlight")
            "npac_on_surface_variant" -> listOf(prefixed, "material_personalized_color_control_normal")
            "npac_primary" -> listOf(prefixed, "material_personalized_color_control_activated")
            "npac_surface_tint",
            "npac_scrim" -> emptyList()
            else -> listOf(prefixed)
        }
    }

    private fun idOf(context: Context, name: String): Int? =
        context.resources.getIdentifier(name, "color", context.packageName).takeIf { it != 0 }

    /**
     * Whether this context is currently showing dark mode.
     *
     * Read from the configuration rather than from [ThemeMode], because by the time an activity reaches `onCreate`
     * AppCompat has already resolved SYSTEM into a concrete night state - and the configuration is the only place that
     * answer exists.
     */
    private fun isDark(context: Context): Boolean =
        context.resources.configuration.uiMode and Configuration.UI_MODE_NIGHT_MASK == Configuration.UI_MODE_NIGHT_YES
}
